### ISSUE TITLE
Any chance alarm for Frame Count?

### ISSUE THREAD

**Issue by BSler** [Admiral-Fish/CitraRNG#1]
First of all great work so far. I know it's early days but I just wanted to know is there any chance in a future update we get an "EONtimer" like countdown within the plugin or script that will automatically press A on a wanted frame in a future update? 

For some reason trying to sync Citra and EONtimer is WAY off for me but slowing down the emulator itself and using the framerate from your plugin has made me a lot more accurate. 

Thanks again for your hard work.

**Comment by Admiral-Fish** [comment]
Not actually sure if scripting support for Citra has the ability to do button presses. I haven't looked into it much but as far as I know it only has read and write memory capabilities currently.

**Comment by Admiral-Fish** [comment]
Out of scope.
