### ISSUE TITLE
citraRNG 3.1.0 won't update 'Main RNG' after loading save state

### ISSUE THREAD

**Issue by ErnestWongGithub** [Admiral-Fish/CitraRNG#11]
Hi,
I am currently playing gen6 ORAS and I have a save state and I am trying for an RNG.
The save state is around 5.5 million frames in, and the 'Main RNG' -> Update no longer works, throwing up the error "Exiting an infinite loop. Make sure no patches are installed..."

Is there a cap on frames before CitraRNG stops working?
Thanks.

**Comment by Admiral-Fish** [comment]
Save states aren't supported
