### ISSUE TITLE
P7ySide6 Not Found

### ISSUE THREAD

**Issue by AsteroidPizza39** [Admiral-Fish/CitraRNG#17]
I installed pyside6 with pip install `pyside6`, but I still receive this error when trying to run `citrarng.py`:

Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

```
====== RESTART: C:\Users\cjcre\AppData\Roaming\Citra\scripting\citrarng.py =====
Traceback (most recent call last):
  File "C:\Users\cjcre\AppData\Roaming\Citra\scripting\citrarng.py", line 2, in <module>
    from PySide6.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PySide6'
```

**Comment by Admiral-Fish** [comment]
Looking online it appears you should try uninstalling and reinstalling pyside6
https://stackoverflow.com/questions/71919812/after-upgrading-pyside6-gives-error-no-module-named-pyside6-qtwidgets
