### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by winterpromo** [Admiral-Fish/CitraRNG#3]
can't connect. but when i play Ultra Moon, Moon connects, and vice versa. the only thing working correctly is the Wild Pokemon profile. please help.

**Comment by Admiral-Fish** [comment]
Have you tried using the latest commit? I have made some changes recently that might have helped with connection stuff.

Also make sure you have the game loaded in Citra before trying to connect.

**Comment by winterpromo** [comment]
okay okay, i'll try dude. thank you. i'll update you, thank you very much.

**Comment by winterpromo** [comment]
cloned the latest commit, but it's still not responding when i connect it with ultra moon. :c help.

**Comment by winterpromo** [comment]
![image](https://user-images.githubusercontent.com/41998949/46707409-64887980-cc6c-11e8-9ef7-c76fc3f5ad48.png)

**Comment by bpxhmemcpy** [comment]
This happens when one is not using version v1.2 as specified in the readme.
Script is reading bogus initial seed then `while currSeed != self.currentSeed` goes into infinite loop (needs a counter and check for >= table size).

Addresses differences for v1.0 are:
```
self.seedAddress = 0x326601C4
self.sfmtStart = 0x330D35CC
self.sfmtIndex = 0x330D3F8C
```

HTH

**Comment by Admiral-Fish** [comment]
Readme says 1.2 for a reason. I don't care to add 1.0. I can probably add a check to make sure initial seed isn't garbage.
