### ISSUE TITLE
struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by dbisop** [Admiral-Fish/CitraRNG#7]
Whenever I open citraRNG and try to connect to the game I get the message 'struct.error: required argument is not an integer' in py.exe and I get this error whether the game is actually open or not. I would just like to know what it is I'm doing wrong, thanks in advance for your time.

**Comment by Admiral-Fish** [comment]
Need more context. What version of CitraRNG, what game, what version of the game?

**Comment by dbisop** [comment]
It's the latest version of citraRNG posted, 3.0.0, and the game is Pokemon Moon on version 1.2

**Comment by Admiral-Fish** [comment]
Should be fixed by 8c1f38d
