### ISSUE TITLE
Unexpected Behaviour in CitraRNG for ORAS

### ISSUE THREAD

**Issue by Gabiusnewelius** [Admiral-Fish/CitraRNG#9]
I followed the instructions to the T, but for some reason CitraRNG behaves weirdly for ORAS.
I patched OR to 1.4 but it gives me the "Initial Seed not valid" error. Meanwhile, on an unpatched Alpha Sapphire, CitraRNG can connect, but as expected the data is garbled and the terminal shows "argument out of range".
Any idea what could be the cause of this?
The error in OR: https://imgur.com/a/olIJsnB
Game patch statuses: https://imgur.com/a/1KMOeWB
AS behaviour: https://imgur.com/a/rqkVQlx

And the build of Citra is the latest Canary on their site (Downloaded today), if maybe (?) that could be a cause.

**Comment by Admiral-Fish** [comment]
Did you install the IPS patch?

**Comment by Gabiusnewelius** [comment]
> 
> 
> Did you install the IPS patch?

Yes. But I looked again at the folder, and renamed it from 00000001 to 00000004 to see if this could be the cause, and it does work now. My mistake!
